package content

import (
	"context"
	"fmt"
	"os"
	"scmp/core/filesystem"
	"scmp/internal/fsops"
	"scmp/internal/logctx"
	"scmp/internal/parsing"
	"scmp/internal/str"
)

// Creates a basic file at the path with JSON metadata header prefilled with example values
func WriteTemplateFile(ctx context.Context, localPath str.LocalRepoPath, userConfirmed bool) {
	path, err := parsing.RetrieveURIFile(ctx, string(localPath))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to parse files URI: %v\n", err)
		os.Exit(1)
	}
	localPath = str.LocalRepoPath(path)

	var fileList []str.LocalRepoPath
	if str.Contains(path, ",") {
		fileList = str.Split(localPath, ",")
	} else {
		fileList = append(fileList, localPath)
	}

	var templateMetadata filesystem.MetaHeader
	templateMetadata.TargetFilePermissions = 600
	templateMetadata.TargetFileOwnerGroup = "root:root"
	templateMetadata.ReloadCommands = []string{"echo check syntax", "echo reload service", "echo check service"}
	templateMetadata.ReloadGroup = "ServiceGroupName"
	templateMetadata.Dependencies = []str.LocalRepoPath{"host/etc/file1", "host/etc/file2"}
	templateMetadata.PreapplyCommands = []string{"stat /var/cache/Dir"}
	templateMetadata.PostapplyCommands = []string{"stat /var/cache/Dir/state"}
	templateMetadata.InstallCommands = []string{"apt-get install curl -y"}
	templateMetadata.PreDeployCommands = []string{"grep -i a <<<{@LOCALFILEDATA}"}

	templateText := "This is a template file generated by SCMP controller using 'controller file new' command\n"
	templateData := []byte(templateText)

	for _, file := range fileList {
		if fsops.FileExists(string(file)) && !userConfirmed {
			logctx.LogStdInfo(ctx, "Warning: Skipping file '%s' because no confirmation was received to overwrite the file\n", file)
			continue
		}

		err = WriteRepoFile(ctx, file, templateMetadata, &templateData)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Failed to write new template file: %v\n", err)
			os.Exit(1)
		}
	}
}
